= Fast 4x4 Matrix Inverse with SSE SIMD, Explained
Eric Zhang
v1.0, 2017-09-03
:toc: macro

:stem: latexmath
:figure-caption!:

toc::[]

Before we start, think about this question: do we really need the inverse of a general matrix?

I came to this problem when writing a math library for my game engine. If you are making a game or 3D application, we use 4x4 matrix for object transform, which is a combination of 3D translation, rotation and scale. If most of your matrix are used as transform matrix, because of their special property, we have a fast route for calculating their inverse. In fact transform matrix inverse is only 50% of the cost compared to the optimized general matrix inverse. In the first half of this post we will talk about transform matrix.  In the second half we will dive in and explain the SIMD version of general 4x4 matrix inverse, and we compare the performance of our method with commonly used math libraries from UE4, Eigen and DirectX Math.

The matrices used in this post are row major. This is mainly for (1) easier to demonstrate and visualize with matrix data layout; (2) easier to compare with other math library. The same matrix inverse function works for both row major and column major, because stem:[A^{-1}=((A^{T})^{-1})^{T}] (inverse is the same as transpose, inverse then transpose again). However if you are a column major guy like myself, I have a full-on column major version for you in <<Appendix>>.

=== Transform Matrix Inverse

The transform matrix we are talking about here is defined as following:

[stem]
++++
M=\left[ \begin{array}{} a\vec{X} & 0 \\ b\vec{Y} & 0 \\ c\vec{Z} & 0 \\ \vec{T} & 1 \\ \end{array} \right] = \left[ \begin{array}{} aX_0 & aX_1 & aX_2 & 0 \\ bY_0 & bY_1 & bY_2 & 0 \\ cZ_0 & cZ_1 & cZ_2 & 0 \\ T_0 & T_1 & T_2 & 1 \\ \end{array} \right]
++++

The first 3 component of the last row is the translation stem:[\vec{T}]. The top left 3x3 sub-matrix is the scaled rotation matrix, with each row as a scaled axis. We have stem:[\vec{X}·\vec{Y}=\vec{X}∙\vec{Z}=\vec{Y}∙\vec{Z}=0], and stem:[\left|\vec{X}\right|=\left|\vec{Y}\right|=\left|\vec{Z}\right|=1]. And the scale is stem:[(a,b,c)]. 

=== General Matrix Inverse


=== Appendix